import type { BlogPost, RichTextNode } from "./types";

const document = (...content: RichTextNode[]): RichTextNode => ({ type: "doc", content });
const heading = (text: string, level = 2): RichTextNode => ({ type: "heading", attrs: { level }, content: [{ type: "text", text }] });
const paragraph = (text: string): RichTextNode => ({ type: "paragraph", content: [{ type: "text", text }] });
const list = (...items: string[]): RichTextNode => ({ type: "bulletList", content: items.map((text) => ({ type: "listItem", content: [paragraph(text)] })) });

export const samplePosts: BlogPost[] = [
  {
    id: "sample-feed",
    title: "How FEED creates safer, more predictable project delivery",
    slug: "how-feed-creates-safer-more-predictable-project-delivery",
    excerpt: "A practical look at how front-end engineering design reduces uncertainty before a project moves into detailed execution.",
    content: document(
      paragraph("Front-end engineering design is where technical decisions become a controlled delivery plan. It aligns process, piping, electrical and instrumentation requirements before cost and schedule commitments harden."),
      heading("Reduce uncertainty before it becomes rework"),
      paragraph("A disciplined FEED phase tests constructability, interfaces, safety requirements and operating constraints early. The result is a stronger basis for tendering, procurement and detailed engineering."),
      list("Define the design basis and governing standards", "Resolve discipline interfaces and critical technical risks", "Create a measurable route into detailed engineering"),
      heading("Engineering clarity supports better investment decisions"),
      paragraph("For operators and EPC teams, the value is not a larger document set. It is a delivery baseline that gives every stakeholder a shared, technically defensible plan.")
    ),
    coverImage: "/media/page-services-hero.png",
    seoTitle: null,
    seoDescription: null,
    seoFocusKeyword: null,
    seoCanonicalUrl: null,
    seoOgTitle: null,
    seoOgDescription: null,
    seoOgImage: null,
    seoTwitterTitle: null,
    seoTwitterDescription: null,
    seoTwitterImage: null,
    seoSchemaType: "BlogPosting",
    seoNoIndex: false,
    authorName: "Saur Engineering Team",
    authorRole: "Engineering Editorial Team",
    status: "published",
    publishedAt: "2026-09-18T09:00:00.000Z",
    createdAt: "2026-09-18T09:00:00.000Z",
    updatedAt: "2026-09-18T09:00:00.000Z",
    categories: ["FEED & Engineering"],
    tags: ["FEED", "Project Delivery", "EPC"],
    techTakeaways: ["FEED reduces uncertainty before procurement and construction commitments harden.", "A shared design basis keeps multidisciplinary teams aligned."],
    relatedPostIds: ["sample-detail-engineering"],
  },
  {
    id: "sample-detail-engineering",
    title: "Detailed engineering deliverables that keep EPC execution moving",
    slug: "detailed-engineering-deliverables-for-epc-execution",
    excerpt: "The drawings, models, calculations and schedules that translate an approved concept into safe, buildable work.",
    content: document(
      paragraph("Detailed engineering turns an approved design into coordinated information that procurement, fabrication and construction teams can use with confidence."),
      heading("One coordinated source of technical truth"),
      paragraph("When drawings, 3D models, calculations, material take-offs and vendor data develop in isolation, downstream teams lose time reconciling conflicting decisions. A multidisciplinary delivery model prevents that drift."),
      list("Issued-for-construction drawings and 3D model coordination", "Equipment, cable, line and material schedules", "Design calculations, datasheets and technical bid support"),
      heading("Quality is built into the handover"),
      paragraph("A well-structured QA/QC process keeps revision control, interdisciplinary checks and client comments visible throughout the work, rather than treating them as a final review task.")
    ),
    coverImage: "/media/expertise-design-office.png",
    seoTitle: null,
    seoDescription: null,
    seoFocusKeyword: null,
    seoCanonicalUrl: null,
    seoOgTitle: null,
    seoOgDescription: null,
    seoOgImage: null,
    seoTwitterTitle: null,
    seoTwitterDescription: null,
    seoTwitterImage: null,
    seoSchemaType: "BlogPosting",
    seoNoIndex: false,
    authorName: "Saur Engineering Team",
    authorRole: "Engineering Editorial Team",
    status: "published",
    publishedAt: "2026-09-15T09:00:00.000Z",
    createdAt: "2026-09-15T09:00:00.000Z",
    updatedAt: "2026-09-15T09:00:00.000Z",
    categories: ["Detailed Engineering"],
    tags: ["3D Modelling", "QA/QC", "Engineering Deliverables"],
    techTakeaways: ["Coordinated deliverables prevent downstream reconciliation work.", "QA/QC works best when it is continuous, not final-stage only."],
    relatedPostIds: ["sample-feed"],
  },
  {
    id: "sample-workforce",
    title: "Building a project-ready engineering workforce",
    slug: "building-a-project-ready-engineering-workforce",
    excerpt: "Why practical software capability, discipline knowledge and project readiness must develop together.",
    content: document(
      paragraph("Engineering capability is more than a list of software tools. Project teams need people who understand design intent, standards, multidisciplinary interfaces and the practical realities of delivery."),
      heading("Training that connects tools to outcomes"),
      paragraph("Targeted development gives engineers a usable workflow: interpreting inputs, building models and drawings, checking outputs and communicating technical decisions clearly."),
      list("Discipline-specific workflow and applicable codes", "Practical CAD and engineering-platform experience", "Readiness for design-office, yard and site environments"),
      heading("A flexible resource model for delivery peaks"),
      paragraph("The right blend of permanent expertise, specialist support and trained deputation helps projects respond to workload changes without compromising technical quality.")
    ),
    coverImage: "/media/page-training-hero.png",
    seoTitle: null,
    seoDescription: null,
    seoFocusKeyword: null,
    seoCanonicalUrl: null,
    seoOgTitle: null,
    seoOgDescription: null,
    seoOgImage: null,
    seoTwitterTitle: null,
    seoTwitterDescription: null,
    seoTwitterImage: null,
    seoSchemaType: "BlogPosting",
    seoNoIndex: false,
    authorName: "Saur Engineering Team",
    authorRole: "Engineering Editorial Team",
    status: "published",
    publishedAt: "2026-09-10T09:00:00.000Z",
    createdAt: "2026-09-10T09:00:00.000Z",
    updatedAt: "2026-09-10T09:00:00.000Z",
    categories: ["Workforce & Training"],
    tags: ["Engineering Training", "Workforce", "Capability"],
    techTakeaways: ["Software capability needs to be tied to discipline judgement.", "Flexible resourcing helps delivery teams respond to peaks without lowering quality."],
    relatedPostIds: ["sample-feed", "sample-detail-engineering"],
  },
];
